// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/fengziwei0826/caching_proxy_exe/internal/cachemanager"
	"github.com/fengziwei0826/caching_proxy_exe/internal/conf"
	"github.com/fengziwei0826/caching_proxy_exe/internal/server"
	"github.com/fengziwei0826/caching_proxy_exe/pkg/db"
)

// Injectors from wire.go:

func InitCacheProxyServer() *server.CacheProxyServer {
	contextContext := context.Background()
	globalConfig := conf.GetGlobalConfig()
	cacheProxy := db.NewCacheProxy(contextContext, globalConfig)
	cacheManager := cachemanager.NewCacheManager(contextContext, cacheProxy)
	httpProxyServer := server.NewHttpProxyServer(contextContext, cacheManager, globalConfig)
	cacheProxyServer := server.NewCacheProxyServer(contextContext, httpProxyServer, globalConfig)
	return cacheProxyServer
}

func InitCacheManager() cachemanager.CacheManager {
	contextContext := context.Background()
	globalConfig := conf.GetGlobalConfig()
	cacheProxy := db.NewCacheProxy(contextContext, globalConfig)
	cacheManager := cachemanager.NewCacheManager(contextContext, cacheProxy)
	return cacheManager
}
