// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/fengziwei0826/caching_proxy_exe/internal/conf"
	"github.com/fengziwei0826/caching_proxy_exe/internal/server"
	"github.com/fengziwei0826/caching_proxy_exe/pkg/db"
)

// Injectors from wire.go:

func InitCacheProxyServer() *server.CacheProxyServer {
	contextContext := context.Background()
	globalConfig := conf.GetGlobalConfig()
	requestCacheProxy := db.NewRequestCacheProxy(contextContext, globalConfig)
	httpProxyServer := server.NewHttpProxyServer(contextContext, requestCacheProxy, globalConfig)
	cacheProxyServer := server.NewCacheProxyServer(contextContext, httpProxyServer, globalConfig)
	return cacheProxyServer
}
